# Generated by Django 5.0.3 on 2024-04-30 10:16

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamentu',
            fields=[
                ('id_departamentu', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('naran_departamentu', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Diresaun',
            fields=[
                ('id_diresaun', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('naran_diresaun', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Fulan',
            fields=[
                ('id_fulan', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('naran_fulan', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Regional',
            fields=[
                ('id_regional', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('naran_regional', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Senhas',
            fields=[
                ('id_senhas', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nu_senhas', models.CharField(max_length=200)),
                ('folin_senhas', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tinan',
            fields=[
                ('ano', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id_transporte', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nu_matricula', models.CharField(max_length=10)),
                ('categoria', models.CharField(choices=[('Kareta', 'Kareta'), ('Motor', 'Motor'), ('Forklif', 'Forklif')], max_length=20)),
                ('tipo_transporte', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('id_user', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('level', models.CharField(choices=[('admin', 'admin'), ('user', 'user')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id_motorista', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('naran_motorista', models.CharField(max_length=200)),
                ('sexo', models.CharField(choices=[('Feto', 'Feto'), ('Mane', 'Mane')], max_length=20)),
                ('id_departamentu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admKombustivel.departamentu')),
                ('id_diresaun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admKombustivel.diresaun')),
                ('id_regional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admKombustivel.regional')),
            ],
        ),
        migrations.CreateModel(
            name='Distribuitor',
            fields=[
                ('id_distribuitor', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('naran_distribuitor', models.CharField(max_length=200)),
                ('montante_distribuitor', models.FloatField(default=0)),
                ('data', models.DateField(default=datetime.date.today)),
                ('ano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admKombustivel.tinan')),
            ],
        ),
        migrations.CreateModel(
            name='Distribuisaun',
            fields=[
                ('id_distribuisaun', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('tipo_kombustivel', models.CharField(choices=[('Gazolina', 'Gazolina'), ('Gazoel', 'Gazoel')], max_length=20)),
                ('destinasaun', models.CharField(max_length=200)),
                ('folin_utilitariu', models.FloatField(max_length=200)),
                ('data', models.DateField(default=datetime.date.today)),
                ('fulan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admKombustivel.fulan')),
                ('id_motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admKombustivel.motorista')),
                ('id_senhas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admKombustivel.senhas')),
                ('ano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admKombustivel.tinan')),
                ('id_transporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admKombustivel.transporte')),
            ],
        ),
    ]
