# Generated by Django 5.0.3 on 2024-04-08 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diresaun',
            fields=[
                ('id_diresaun', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('naran_diresaun', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Fulan',
            fields=[
                ('id_fulan', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('naran_fulan', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Kompanhia',
            fields=[
                ('id_kompanhia', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('naran_kompanhia', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id_motorista', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('naran_motorista', models.CharField(max_length=200)),
                ('sexo', models.CharField(choices=[('Feto', 'Feto'), ('Mane', 'Mane')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Regional',
            fields=[
                ('id_regional', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('regional', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Senhas',
            fields=[
                ('id_senhas', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('nu_senhas', models.CharField(max_length=200)),
                ('folin_senhas', models.FloatField(default=0, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tinan',
            fields=[
                ('ano', models.IntegerField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id_transporte', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('nu_matricula', models.CharField(max_length=10)),
                ('categoria', models.CharField(choices=[('Kareta', 'Kareta'), ('Motor', 'Motor'), ('Forklif', 'Forklif')], max_length=20)),
                ('tipo_kareta', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('id_user', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('level', models.CharField(choices=[('admin', 'admin'), ('user', 'user')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Kombustivel',
            fields=[
                ('id_kombustivel', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('kategoria', models.CharField(choices=[('Gazolina', 'Gazolina'), ('Gazoel', 'Gazoel')], max_length=20)),
                ('id_diresaun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admKombustivel.diresaun')),
                ('id_senhas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admKombustivel.fulan')),
                ('id_kompanhia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admKombustivel.kompanhia')),
                ('id_fulan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admKombustivel.senhas')),
                ('ano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admKombustivel.tinan')),
                ('id_transporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admKombustivel.transporte')),
            ],
        ),
    ]
