# Generated by Django 5.0.3 on 2024-04-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admKombustivel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribuisaun',
            name='kilometrajen',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
