# Generated by Django 5.0.3 on 2024-05-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admKombustivel', '0002_distribuisaun_kilometrajen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulan',
            name='id_fulan',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
