# Generated by Django 5.0.3 on 2024-05-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admKombustivel', '0003_alter_fulan_id_fulan'),
    ]

    operations = [
        migrations.AddField(
            model_name='senhas',
            name='status',
            field=models.CharField(choices=[('Seidauk Distribui', 'Seidauk Distribui'), ('Distribui Ona', 'Distribui Ona')], default='Seidauk Distribui', max_length=20),
        ),
    ]
