# Generated by Django 5.0.3 on 2024-05-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admKombustivel', '0005_distribuitorrelatorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribuitor',
            name='montante_atual',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='DistribuitorRelatorio',
        ),
    ]
