from django.urls import path
from . import views
urlpatterns = [
     path('login/', views.loginPage, name='login'),
     path('logout/', views.logoutUser, name='logout'),
     path('', views.dash_kombustivel, name='dash_kombustivel'),
     path('dadus_distributor/', views.dadus_distributor, name='dadus_distributor'),
     path('aumenta_distributor/', views.aumenta_distributor, name='aumenta_distributor'),
     path('delete_dadus_distributor/<str:pk>/', views.delete_dadus_distributor, name='delete_dadus_distributor'),
     path('update_dadus_distributor/<str:pk>/', views.updateDistributor, name='updateDistributor'),
     path('distribui_kom/', views.distribui_kom, name='distribui_kom'),
     path('aumenta_dadus_distribuisaun/', views.aumenta_dadus_distribuisaun, name='aumenta_dadus_distribuisaun'),
     path('senhas/', views.senhas, name='dadus_senhas'),
     path('aumenta_dadus_senhas/', views.aumenta_dadus_senhas, name='aumenta_dadus_senhas'),
     path('delete_dadus_senhas/<str:pk>/', views.delete_dadus_senhas, name='delete_dadus_senhas'),
     path('update_senhas/<str:pk>/', views.updateSenhas, name='updateSenhas'),
     path('dadus_regional/', views.dadus_regional, name='dadus_regional'),
     path('aumenta_dadus_regional/', views.aumenta_dadus_regional, name='aumenta_dadus_regional'),
     path('delete_dadus_regional/<str:pk>/', views.delete_dadus_regional, name='delete_dadus_regional'),
     path('update_regional/<str:pk>/', views.updateRegional, name='updateRegional'),
     path('dadus_departamentu/', views.dadus_departamentu, name='dadus_departamentu'),
     path('aumenta_dadus_departamentu/', views.aumenta_dadus_departamentu, name='aumenta_dadus_departamentu'),
     path('delete_dadus_departamentu/<str:pk>/', views.delete_dadus_departamentu, name='delete_dadus_departamentu'),
     path('update_departamentu/<str:pk>/', views.updateDepartamentu, name='updateDepartamentu'),
     path('dadus_diresaun/', views.dadus_diresaun, name='dadus_diresaun'),
     path('aumenta_dadus_diresaun/', views.aumenta_dadus_diresaun, name='aumenta_dadus_diresaun'),
     path('delete_dadus_diresaun/<str:pk>/', views.delete_dadus_diresaun, name='delete_dadus_diresaun'),
     path('update_diresaun/<str:pk>/', views.updateDiresaun, name='updateDiresaun'),
     path('dadus_fulan/', views.dadus_fulan, name='dadus_fulan'),
     path('aumenta_dadus_fulan/', views.aumenta_dadus_fulan, name='aumenta_dadus_fulan'),
     path('delete_dadus_fulan/<str:pk>/', views.delete_dadus_fulan, name='delete_dadus_fulan'),
     path('update_fulan/<str:pk>/', views.updateFulan, name='updateFulan'),
     path('dadus_tinan/', views.dadus_tinan, name='dadus_tinan'),
     path('delete_dadus_tinan/<str:pk>/', views.delete_dadus_tinan, name='delete_dadus_tinan'),
     path('aumenta_dadus_tinan/', views.aumenta_dadus_tinan, name='aumenta_dadus_tinan'),
     path('update_tinan/<str:pk>/', views.updateTinan, name='updateTinan'),
     path('dadus_trans/', views.dadus_trans, name='dadus_trans'),
     path('aumenta_dadus_trans/', views.aumenta_dadus_trans, name='aumenta_dadus_transporte'),
     path('delete_dadus_trans/<str:pk>/', views.delete_dadus_transporte, name='delete_dadus_transporte'),
     path('updatetransporte/<str:pk>/', views.updateTransporte, name='updateTransporte'),
     path('dadus_motorista/', views.dadus_motorista, name='dadus_motorista'),
     path('aumenta_dadus_motorista/', views.aumenta_dadus_motorista, name='aumenta_dadus_motorista'),
     path('delete_dadus_motorista/<str:pk>/', views.delete_dadus_motorista, name='delete_dadus_motorista'),
     path('update_motorista/<str:pk>/', views.updateMotorista, name='updateMotorista'),
     path('aumenta_admin/', views.aumenta_admin, name='aumenta_admin'),  
     path('edit_admin/', views.edit_admin, name='edit_admin'),

]